name: obiq_bridge
description: "A custom Flutter package designed for the Obiq Launcher."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: app.obiq.bridge
        pluginClass: ObiqBridgePlugin
